export enum TrackEvent {
  UploadReceived = 'track.upload.received',
  UploadValidated = 'track.upload.validated',
  UploadStored = 'track.upload.stored',
  Uploaded = 'track.uploaded',
  UploadFailed = 'track.upload.failed',
  PetrifiedGenerated = 'track.petrified.generated',
  PetrifiedSongFound = 'track.petrified.song.found',
  PetrifiedSongUnknown = 'track.petrified.song.unknown',
  PetrifiedDetected = 'track.petrified.detected',
  PetrifiedFailed = 'track.petrified.failed',
  DuplicateDetected = 'track.duplicate.detected',
  FortMinorStarted = 'track.fort-minor.started',
  FortMinorCompleted = 'track.fort-minor.completed',
  FortMinorFailed = 'track.fort-minor.failed',
  StereoStarted = 'track.stereo.started',
  Approved = 'track.approved',
  Rejected = 'track.rejected',
  StereoFailed = 'track.stereo.failed',
  TranscodingStarted = 'track.transcoding.started',
  TranscodingCompleted = 'track.transcoding.completed',
  TranscodingFailed = 'track.transcoding.failed',
  HlsGenerated = 'track.hls.generated',
  HlsStored = 'track.hls.stored',
  HlsFailed = 'track.hls.failed'
}
